proxy-groups:
  - name: èŠ‚ç‚¹é€‰æ‹©
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - æ•…éšœè½¬ç§»
      - è½åœ°èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ¾³é—¨èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - è‹±å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - æ³•å›½èŠ‚ç‚¹
      - åŠ æ‹¿å¤§èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: æ‰‹åŠ¨åˆ‡æ¢
    icon: https://cdn.jsdmirror.com/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: å‰ç½®ä»£ç†
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Area.png
    type: select
    include-all: true
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ¾³é—¨èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - è‹±å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - æ³•å›½èŠ‚ç‚¹
      - åŠ æ‹¿å¤§èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: è½åœ°èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Airport.png
    type: select
    include-all: true
    filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°
  - name: æ•…éšœè½¬ç§»
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    proxies:
      - è½åœ°èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ¾³é—¨èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - è‹±å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - æ³•å›½èŠ‚ç‚¹
      - åŠ æ‹¿å¤§èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
    interval: 180
    tolerance: 20
    lazy: false
  - name: é™æ€èµ„æº
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    proxies: &a1
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ¾³é—¨èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - è‹±å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - æ³•å›½èŠ‚ç‚¹
      - åŠ æ‹¿å¤§èŠ‚ç‚¹
      - ä½å€ç‡èŠ‚ç‚¹
      - æ‰‹åŠ¨åˆ‡æ¢
      - ç›´è¿
  - name: AI
    icon: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/icons/OpenAI.png
    type: select
    proxies: *a1
  - name: Telegram
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies: *a1
  - name: YouTube
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a1
  - name: Netflix
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a1
  - name: Spotify
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a1
  - name: TikTok
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a1
  - name: E-Hentai
    icon: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies: *a1
  - name: PikPak
    icon: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/icons/PikPak.png
    type: select
    proxies: *a1
  - name: Truth Social
    icon: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/icons/TruthSocial.png
    type: select
    proxies:
      - ç¾å›½èŠ‚ç‚¹
      - èŠ‚ç‚¹é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
  - name: å“”å“©å“”å“©
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - ç›´è¿
      - å°æ¹¾èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
  - name: æµ‹é€Ÿ
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
    type: select
    proxies: *a1
  - name: SSH(22ç«¯å£)
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Server.png
    type: select
    proxies: *a1
  - name: æœç‹—è¾“å…¥æ³•
    icon: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/icons/Sougou.png
    type: select
    proxies:
      - ç›´è¿
      - REJECT
  - name: ç›´è¿
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - èŠ‚ç‚¹é€‰æ‹©
  - name: å¹¿å‘Šæ‹¦æˆª
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - ç›´è¿
  - name: ä½å€ç‡èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Lab.png
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    include-all: true
    filter: (?i)0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
  - name: é¦™æ¸¯èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)é¦™æ¸¯|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|ğŸ‡­ğŸ‡°
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: æ¾³é—¨èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Macao.png
    include-all: true
    filter: (?i)æ¾³é—¨|MO|Macau|ğŸ‡²ğŸ‡´
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: å°æ¹¾èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|ğŸ‡¹ğŸ‡¼
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: ç¾å›½èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)ç¾å›½|ç¾|US|United States|ğŸ‡ºğŸ‡¸
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: è‹±å›½èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/United_Kingdom.png
    include-all: true
    filter: (?i)è‹±å›½|United Kingdom|UK|ä¼¦æ•¦|London|ğŸ‡¬ğŸ‡§
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: æ—¥æœ¬èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: éŸ©å›½èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Korea.png
    include-all: true
    filter: (?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“|ğŸ‡°ğŸ‡·
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: æ–°åŠ å¡èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: å¾·å›½èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Germany.png
    include-all: true
    filter: (?i)å¾·å›½|å¾·|DE|Germany|ğŸ‡©ğŸ‡ª
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: æ³•å›½èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/France.png
    include-all: true
    filter: (?i)æ³•å›½|æ³•|FR|France|ğŸ‡«ğŸ‡·
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: åŠ æ‹¿å¤§èŠ‚ç‚¹
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Canada.png
    include-all: true
    filter: (?i)åŠ æ‹¿å¤§|Canada|CA|ğŸ‡¨ğŸ‡¦
    exclude-filter: (?i)å®¶å®½|å®¶åº­|å®¶åº­å®½å¸¦|å•†å®½|å•†ä¸šå®½å¸¦|æ˜Ÿé“¾|Starlink|è½åœ°|0.[0-5]|ä½å€ç‡|çœæµ|å¤§æµé‡|å®éªŒæ€§
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: GLOBAL
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - æ‰‹åŠ¨åˆ‡æ¢
      - å‰ç½®ä»£ç†
      - è½åœ°èŠ‚ç‚¹
      - æ•…éšœè½¬ç§»
      - é™æ€èµ„æº
      - AI
      - Telegram
      - YouTube
      - Netflix
      - Spotify
      - TikTok
      - E-Hentai
      - PikPak
      - Truth Social
      - å“”å“©å“”å“©
      - æµ‹é€Ÿ
      - SSH(22ç«¯å£)
      - æœç‹—è¾“å…¥æ³•
      - ç›´è¿
      - å¹¿å‘Šæ‹¦æˆª
      - ä½å€ç‡èŠ‚ç‚¹
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ¾³é—¨èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - è‹±å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ–°åŠ å¡èŠ‚ç‚¹
      - å¾·å›½èŠ‚ç‚¹
      - æ³•å›½èŠ‚ç‚¹
      - åŠ æ‹¿å¤§èŠ‚ç‚¹
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ruleset/ADBlock.txt
  TruthSocial:
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/TruthSocial.list
    path: ./ruleset/TruthSocial.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  AI:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./ruleset/AI.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdmirror.com/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  SpeedTest:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/speedtest.txt
    path: ./ruleset/SpeedTest.list
rules:
  - RULE-SET,ADBlock,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,AdditionalFilter,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,SogouInput,æœç‹—è¾“å…¥æ³•
  - RULE-SET,TruthSocial,Truth Social
  - RULE-SET,StaticResources,é™æ€èµ„æº
  - RULE-SET,CDNResources,é™æ€èµ„æº
  - RULE-SET,AdditionalCDNResources,é™æ€èµ„æº
  - RULE-SET,AI,AI
  - RULE-SET,EHentai,E-Hentai
  - RULE-SET,TikTok,TikTok
  - RULE-SET,SteamFix,ç›´è¿
  - RULE-SET,GoogleFCM,ç›´è¿
  - RULE-SET,SpeedTest,æµ‹é€ŸæœåŠ¡
  - GEOSITE,GOOGLE-PLAY@CN,ç›´è¿
  - GEOSITE,TELEGRAM,Telegram
  - GEOSITE,YOUTUBE@CN,ç›´è¿
  - GEOSITE,YOUTUBE,YouTube
  - GEOSITE,NETFLIX,Netflix
  - GEOSITE,SPOTIFY,Spotify
  - GEOSITE,BILIBILI,å“”å“©å“”å“©
  - GEOSITE,CATEGORY-SCHOLAR-CN,ç›´è¿
  - GEOSITE,MICROSOFT@CN,ç›´è¿
  - GEOSITE,PIKPAK,PikPak
  - GEOSITE,GFW,èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,CN,ç›´è¿
  - GEOSITE,PRIVATE,ç›´è¿
  - GEOIP,NETFLIX,Netflix,no-resolve
  - GEOIP,TELEGRAM,Telegram,no-resolve
  - GEOIP,CN,ç›´è¿
  - GEOIP,PRIVATE,ç›´è¿
  - DST-PORT,22,SSH(22ç«¯å£)
  - MATCH,èŠ‚ç‚¹é€‰æ‹©
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - quic://223.5.5.5
    - tls://dot.pub
    - tls://dns.alidns.com
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - quic://223.5.5.5
    - tls://dot.pub
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdmirror.com/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdmirror.com/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdmirror.com/gh/Loyalsoldier/geoip@release/Country.mmdb
  asn: https://cdn.jsdmirror.com/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb

